GO
USE ISS_PRACTICE;
GO
CREATE TABLE EMPLOYEES
(
ID INT PRIMARY KEY IDENTITY(1,1), 
EMP_NAME VARCHAR(30) NOT NULL, 
AGE INT, ADDRESS VARCHAR(100), 
OFFICE_LOCATION VARCHAR(20), 
EXPERIENCE INT 
);
GO
INSERT INTO EMPLOYEES
(EMP_NAME, AGE, ADDRESS, OFFICE_LOCATION, EXPERIENCE) 
VALUES
('BENJAMIN JOHNSON',35, '123 OAK STREET', 'NEW YORK', 7);
GO
INSERT INTO EMPLOYEES
(EMP_NAME, AGE, ADDRESS, OFFICE_LOCATION, EXPERIENCE) 
VALUES
('SOPHIA RODRIGUEZ',28, '456 MAPLE AVENUE', 'TORONTO', 4);
GO
INSERT INTO EMPLOYEES
(EMP_NAME, AGE, ADDRESS, OFFICE_LOCATION, EXPERIENCE) 
VALUES
('LUCA ROSSI',32, '789 PINE LANE', 'ROME', 6);
GO
INSERT INTO EMPLOYEES
(EMP_NAME, AGE, ADDRESS, OFFICE_LOCATION, EXPERIENCE) 
VALUES
('MIA GARCIA',40, '101 CEDAR ROAD', 'BARCELONA',9);
GO
INSERT INTO EMPLOYEES
(EMP_NAME, AGE, ADDRESS, OFFICE_LOCATION, EXPERIENCE) 
VALUES
('EMMA KIM',24, '505 MAPLE DRIVE', 'SEOUL', 2);
GO
INSERT INTO EMPLOYEES
(EMP_NAME, AGE, ADDRESS, OFFICE_LOCATION, EXPERIENCE) 
VALUES
('LIAM NGUYEN',38, '404 PINE STREET', 'SYDNEY', 8);
GO
INSERT INTO EMPLOYEES
(EMP_NAME, AGE, ADDRESS, OFFICE_LOCATION, EXPERIENCE) 
VALUES
('ISABELLA SMITH',30, '303 BIRCH LANE', 'LONDON', 5);
GO
INSERT INTO EMPLOYEES
(EMP_NAME, AGE, ADDRESS, OFFICE_LOCATION, EXPERIENCE) 
VALUES
('OLIVER MÜLLER',26, '202 ELM DRIVE', 'BERLIN', 3);
GO
SELECT * FROM EMPLOYEES