USE ISS_PRACTICE;

DELETE FROM EMPLOYEES WHERE ID=8; 

CREATE TABLE EMPLOYEES_PROJECTS(PROJECT_ID INT PRIMARY KEY IDENTITY(1,1), PROJECT_NAME VARCHAR(50), EMPLOYEE_ID INT REFERENCES EMPLOYEES(ID));

INSERT INTO EMPLOYEES_PROJECTS(PROJECT_NAME, EMPLOYEE_ID) VALUES('EMPLOYEE MANAGEMENT SYSTEM', 4);

INSERT INTO EMPLOYEES_PROJECTS(PROJECT_NAME, EMPLOYEE_ID) VALUES('STUDENT RESULT DASHBOARD', 6);

INSERT INTO EMPLOYEES_PROJECTS(PROJECT_NAME, EMPLOYEE_ID) VALUES('TRAVEL MANAGEMENT SYSTEM', 5);

INSERT INTO EMPLOYEES_PROJECTS(PROJECT_NAME, EMPLOYEE_ID) VALUES('RESTAURANT MANAGEMENT SYSTEM', 3);

INSERT INTO EMPLOYEES_PROJECTS(PROJECT_NAME, EMPLOYEE_ID) VALUES('BLOOD DONATION MANAGEMENT SYSTEM', 7);

INSERT INTO EMPLOYEES_PROJECTS(PROJECT_NAME, EMPLOYEE_ID) VALUES('HOTEL MANAGEMENT SYSTEM', 5);

INSERT INTO EMPLOYEES_PROJECTS(PROJECT_NAME, EMPLOYEE_ID) VALUES ('COLLEGE SYSTEM', 7);

SELECT * FROM EMPLOYEES_PROJECTS;

ALTER TABLE EMPLOYEES_PROJECTS ADD CHECK (PROJECT_NAME LIKE '%SYSTEM' OR PROJECT_NAME LIKE '%DASHBOARD' OR PROJECT_NAME LIKE '%WEBSITE' OR PROJECT_NAME LIKE '%PROJECT');

SELECT ID FROM EMPLOYEES UNION ALL SELECT EMPLOYEE_ID FROM EMPLOYEES_PROJECTS;

SELECT EMPLOYEE_ID, COUNT(*) AS ProjectCount FROM EMPLOYEES_PROJECTS GROUP BY EMPLOYEE_ID;

SELECT * FROM EMPLOYEES INNER JOIN EMPLOYEES_PROJECTS ON ID=EMPLOYEE_ID;

SELECT * FROM EMPLOYEES LEFT JOIN EMPLOYEES_PROJECTS ON ID=EMPLOYEE_ID;

SELECT * FROM EMPLOYEES RIGHT JOIN EMPLOYEES_PROJECTS ON ID=EMPLOYEE_ID;

SELECT * FROM EMPLOYEES FULL JOIN EMPLOYEES_PROJECTS ON ID=EMPLOYEE_ID;

