USE ISS_PRACTICE;
SELECT * FROM EMPLOYEES;
GO
UPDATE EMPLOYEES SET OFFICE_LOCATION='PARIS' WHERE ID=7;
SELECT * FROM EMPLOYEES;
GO
SELECT * FROM EMPLOYEES WHERE ADDRESS LIKE '%PINE%';
GO
SELECT * FROM EMPLOYEES WHERE AGE BETWEEN 30 AND 40;
GO
SELECT ID,EMP_NAME FROM EMPLOYEES WHERE OFFICE_LOCATION IN ('PARIS', 'ROME', 'BARCELONA', 'BERLIN');
GO
SELECT * FROM EMPLOYEES WHERE OFFICE_LOCATION LIKE '_E_L_N';
GO
SELECT * FROM EMPLOYEES WHERE OFFICE_LOCATION LIKE 'SEOUL';
GO
SELECT ID, EMP_NAME,EXPERIENCE, AGE FROM EMPLOYEES WHERE AGE>35 AND EXPERIENCE>5;
GO
SELECT ID, EMP_NAME,EXPERIENCE, AGE FROM EMPLOYEES WHERE AGE>35 OR EXPERIENCE>5;
GO
SELECT * FROM EMPLOYEES ORDER BY EXPERIENCE;
GO
SELECT * FROM EMPLOYEES ORDER BY EXPERIENCE DESC;
GO
SELECT ID, EMP_NAME, OFFICE_LOCATION AS 'OFFICE_POSTING' FROM EMPLOYEES;
GO
SELECT TOP 3 *
FROM EMPLOYEES
WHERE AGE > 30;